baseURL: https://hugo-emergency-site.netlify.app/
title: Site d'urgence avec Hugo

languageCode: fr
defaultContentLanguage: fr

author:
  name: Nicolas Friedli
  email: nicolasfriedli@protonmail.ch
  phone: +41 32 481 48 74

canonifyURLs: true
disableFastRender: true

disableKinds:
  - taxonomy
  - taxonomyTerm
  
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      typographer: true
    parser:
      autoHeadingIDType: github-ascii

params:
  title: Site d'urgence avec Hugo
  description: Copier Max Böck pour apprendre!
